export const Strategies = [
  { id: 1, text: 'Write a test' },
  { id: 2, text: 'Brute force first' },
  { id: 3, text: 'Keep it simple' },
  { id: 4, text: 'Draw a diagram' },
  { id: 5, text: 'How do other libraries do it?' },
  { id: 6, text: 'Can it be simpler?' },
  { id: 7, text: 'Simple subtraction' },
  { id: 8, text: 'Junk it' },
  { id: 9, text: 'Turn it upside down' },
  { id: 10, text: 'Show someone else' },
  { id: 11, text: 'A line has two sides' },
  { id: 12, text: 'Look for similar examples' },
  { id: 13, text: 'Breathe more deeply' },
  { id: 14, text: 'Emphasize differences' },
  { id: 15, text: 'Tidy up' },
  { id: 16, text: 'Abandon normal instruments' },
  { id: 17, text: 'What mistakes did you make last time?' },
  { id: 18, text: 'Work at a different speed' },
  { id: 19, text: 'Emphasize the flaws' },
  { id: 20, text: 'Take a break' },
  { id: 21, text: 'Use an old idea' },
  { id: 22, text: 'Ask a user' },
  { id: 23, text: 'Not building a wall but making a brick' },
  { id: 24, text: 'Would anybody want it?' },
  { id: 25, text: 'Only a part, not the whole' },
  { id: 26, text: 'Go to an extreme, move back to a more comfortable place' },
  { id: 27, text: 'Break a big thing up into smaller pieces' },
  { id: 28, text: 'Are you solving the right problem?' },
  { id: 29, text: 'Can you automate this?' },
  { id: 30, text: 'Water' },
  { id: 31, text: 'Check open and closed issues on GitHub' },
  { id: 32, text: 'Check the recent releases' },
  { id: 33, text: 'Google it' },
  { id: 34, text: 'How will this be maintained?' },
  { id: 35, text: 'Explain it to someone else' }
];
